### ISSUE TITLE
Requesting multi-color light setup.

### ISSUE THREAD

**Issue by BugMonkey42335** [FlailingFog/KK-Blender-Porter-Pack#110]
Is it be possible to implement the multi-color light setup as described in this video into the KK Shader?

[Toon Shader Tutorial - Part 1 - How to Have Multiple Light Sources](https://www.youtube.com/watch?v=TpWI2rU8iF0&list=PLZ7TSA6MfgM_IX3qZslXx_QdvLLDZHZGx&index=1)

**Comment by FlailingFog** [comment]
I probably won't implement this into the shader, but I did put a separate RGB node in at least. It's in the raw shading node group
![image](https://user-images.githubusercontent.com/65811931/155863408-1d6809a8-cb9e-48fc-a7f9-a6ec002e400b.png)

If you want to implement it yourself though, you can just [download the shader from the code page](https://github.com/FlailingFog/KK-Blender-Porter-Pack), take the G and B outputs, feed them into the shader group and layer the additional things that he shows between the mix node and the output node inside the shader group
![image](https://user-images.githubusercontent.com/65811931/155863515-214f3e24-53a0-4f90-af47-77834d94ace4.png)

Then whenever you want to use the new setup, you can just drop your modified KK Shader.blend into the same directory your pmx file is in and the plugin will automatically use your modified blend instead of the integrated one
