### ISSUE TITLE
Please add KS support

### ISSUE THREAD

**Issue by Fractune** [FlailingFog/KK-Blender-Porter-Pack#123]
If possible to add Koikatsu Sunshine support? I tried this & I didn't see the UI thus I have everything there instead of Koikatsu Party.. Transferring the card images to Koikatsu Party's female folder wont work either 'cause it doesn't show cards from Sunshine.

**Comment by im-pain** [comment]
i think the tool GME need to be updated for that so until that he cant do anything about it

**Comment by im-pain** [comment]
i think the tool GME need to be updated for that so until that he cant do anything about it

**Comment by MediaMoots** [comment]
The reason I haven't updated KKBP Exporter to KS is because i am unable to install KS on my system right now, but i hope to fix that in the future, in the meantime I'm afraid you will have to keep using older versions...

**Comment by poisenbery** [comment]
> KKBP Exporter

Please post the source code.
Illusion games are similar enough that they don't require too much work to port from game to game.

I'm working on porting PMXExport.dll to KKS, but I have a feeling my life would be easier if you could post the source code for YOUR plugin, since the source code for PMXExport.dll isn't anywhere [I'm pretty sure you know this already though ;)]

**Comment by MediaMoots** [comment]
https://user-images.githubusercontent.com/81146974/172015702-b08db3e3-2782-497b-83c3-dee4ab723606.gif
PR #138
