### ISSUE TITLE
Face issue

### ISSUE THREAD

**Issue by ZaverVT** [FlailingFog/KK-Blender-Porter-Pack#163]
![L88POSk3Gz](https://user-images.githubusercontent.com/106369144/170639767-f1edc3f7-41e6-4e86-9e1a-a884f908a722.png)

I'm getting this issue when I'm importing the KK Shaders for a model I made in Koikatsu.  It only happens with models that use Face 2 as the face.  Models that use face 1 are fine.

**Comment by poisenbery** [comment]
managed to reproduce the error with a test character with a face 2.

Face2 seems to have a different naming convention than Face 1. Because of this, it gets added to the clothing object during the "Finalize PMX" step. When you try to apply the shader pack, it tried to apply the "Face Template" to the face material, which should be in the body object, but alas, it's not there because it was placed in the clothing object.


Until a fix is posted, I manage to get a face2 model to load by taking the following steps:
1.) Import the model
2.) Before pressing "Finalize PMX," select the Model_mesh object [the model itself]
3.) In the Properties Panel, go to the Material Properties tab
4.) Look for the "cf_m_face_02 -[numbers]" material.
5.) Rename this to "cf_m_face_00" without quotes
6.) Click "Finalize PMX" and proceed as usual
![Screenshot (587)](https://user-images.githubusercontent.com/78466408/170891478-68c3ce29-539c-42dd-b537-cac3c1efc9c0.png)

**Comment by ZaverVT** [comment]
Thank you, that helped.  I had to also go into the texture files to rename those to get the face textures to import correctly as well, but it worked nonetheless.

**Comment by FlailingFog** [comment]
It should import without errors in https://github.com/FlailingFog/KK-Blender-Porter-Pack/pull/138 now, but you'll still have to load in one or two textures manually
