### ISSUE TITLE
Misaligned part of hair on model?

### ISSUE THREAD

**Issue by BeamingTerror** [FlailingFog/KK-Blender-Porter-Pack#169]
![image](https://user-images.githubusercontent.com/106932455/172071650-e0753e51-aef7-4b10-bf28-86e6abe7897e.png)

All of the hair on this model is in the accessories tab.
Why is part of it misaligned, and there is extra hair? It's all a very confusing mess

This happens when i import the pmx, and the problem persists after completing all the steps.

this didn't happen with any other character before, and I've tried importing again with different outfits but no luck.

Here is the card:
![86321225_p4](https://user-images.githubusercontent.com/106932455/172071751-b16fe269-5f67-4f8a-b161-000711f238f2.png)

Forgive me if my format is weird or I did something wrong; I'm new to github.

**Comment by FlailingFog** [comment]
The hair exports correctly, but the author of the card made the file that turns the hair invisible use the color channel instead of the alpha channel. I'll add a fix for this.
![image](https://user-images.githubusercontent.com/65811931/172076718-957bcd31-df4f-422f-8862-f7ede5bc8e55.png)
![image](https://user-images.githubusercontent.com/65811931/172076558-eb3adb5e-6b4a-4141-a0a9-503dda9225b9.png)

**Comment by BeamingTerror** [comment]
Thanks for your response and assistance, your help is greatly appreciated :D
