### ISSUE TITLE
Rigify convertion get an error

### ISSUE THREAD

**Issue by OneGraves** [FlailingFog/KK-Blender-Porter-Pack#175]
when trying to convert to rigify after creating the metarig I get an error
I included the card
![Koikatu_F_20210803121127945_Xiangling_mr-based](https://user-images.githubusercontent.com/83756910/173031557-ea2675d2-caed-46f6-90b2-56035a512210.png)

Python: Traceback (most recent call last):
  File "C:\Users\OneGraves\AppData\Roaming\Blender Foundation\Blender\3.1\scripts\addons\KK-Blender-Porter-Pack-master\extras\rigifywrapper.py", line 36, in execute
    bpy.ops.pose.rigify_generate()
  File "C:\Program Files\Blender Foundation\Blender 3.1\3.1\scripts\modules\bpy\ops.py", line 132, in __call__
    ret = _op_call(self.idname_py(), None, kw)
RuntimeError: Error: RIGIFY ERROR: Bone 'cf_j_sk_00_00': Input to rig type must be a chain of 2 or more bones.
Incorrect armature for type 'chain_rigs'

location: <unknown location>:-1

**Comment by OneGraves** [comment]
Found the issue, when the skirt bones are not connected to the hips bone the rigify conversion to rigify gets an error

**Comment by ilcane87** [comment]
Hi @OneGraves, I tried converting your character without altering any bone relationships and everything worked smoothly:

![image](https://user-images.githubusercontent.com/34897042/173082551-2db47c71-16c1-4b11-a360-c28cc96341e2.png)

Also, the skirt bones don't have to be connected to the hips bone, they only have to be connected among themselves and to their parent bones.
Can you verify that they look like the picture below in the original armature before you convert it to a metarig?

![image](https://user-images.githubusercontent.com/34897042/173083079-180be44d-9200-4944-8177-f4fb808a9859.png)

There's actually another user who had the same error not long ago, and it turned out it was an import mistake on his end, you can check out his issue here: https://github.com/FlailingFog/KK-Blender-Porter-Pack/issues/149

**Comment by sleepymanakete** [comment]
Yeah, make sure to use the "import model" button on the cats addon. that was the mistake I made... 😅

on an unrelated note, I'd like to correct that I'm a she xD
