### ISSUE TITLE
Blender crashes when clicking add shapekeys

### ISSUE THREAD

**Issue by NerdyB1443** [FlailingFog/KK-Blender-Porter-Pack#20]

**Comment by NerdyB1443** [comment]
Issue persists after the new update.

**Comment by auronx223** [comment]
Having the same issue, initially it throws an exception saying it cannot find "cf_m_sirome_00" the model seems to be using a material called "Template Eyewhites (sirome)". When I rename it to cf_m_sirome_00 that its expecting it just crashes blender entirely.

Tested using version V4.2.2

**Comment by FlailingFog** [comment]
@NerdyB1443 I can only get it to crash consistently if I don't click the wrench icon next to the Fix Model button and set the options correctly. If you're sure you changed the wrench options from the defaults before you clicked the Fix Model button then I'm not sure what the issue could be (it should have the top three enabled and the bottom three disabled).
I also don't know why it's crashing if the options are set incorrectly in the first place.

@auronx223 I think this is a different cause, the plugin expects you to use the shapekeys button **_before_** you import the material templates. I can probably make it so it works both ways

**Comment by auronx223** [comment]
I originally ran it before importing the material templates but didn't realise it hadn't fully worked until testing later on.

Running through again it still shows an error which happened the first time where pressing fix shapekeys will throw an error and be in edit mode instead of object mode. When pressing fix model in CATS I checked first three options and de-selected last three before doing the fix shapekeys.

![Error](https://user-images.githubusercontent.com/9289155/121687042-cb176280-cab9-11eb-8904-61615013c4b2.png)

**Comment by auronx223** [comment]
Testing on a new model it looks like it has the same issue where pressing fix shapekeys gets stuck halfway and throws an error with it being in edit mode.

Interestingly it seems to delete the mesh for right sirome when it fails.

I tried merging the two sirome together to see if it helps and it causes Blender to crash when I press fix shapekeys. It might be the issue NerdyB1443 has where they might have merged the two materials together.

**Comment by FlailingFog** [comment]
I still don't know why it's crashing, but through process of elimination the only thing left that could be causing it are the eyewhite operations that are part of the shapekeys script, so I added a toggle to disable it in V4.2.3
