### ISSUE TITLE
6.0 How to use beta...

### ISSUE THREAD

**Issue by NioN80** [FlailingFog/KK-Blender-Porter-Pack#200]
I have installed a new version of the Koykatsu Export Plug-in, 6.0 Beta, in Blander 3.2. However, there are many differences from the previous version of 5.1.1.The 'finalize PMX file' and 'import kkshader and texture' buttons have disappeared, so I don't know what steps to take after I bring the model... 

I'm sorry to ask you a stupid question.The image below is the model loaded.
![image](https://user-images.githubusercontent.com/89737013/178122880-c1ce40cf-be20-40c6-8bba-4ac5def6673e.png)

**Comment by LuluViBritannia012** [comment]
I'm not the dev, but since I've used it, here's the answer (I don't know if this is the proper behavior on github, sorry if that's not).

1) You click Import Model and choose the pmx file (as you would with the stable version). There's many of them, but choose the one that isn't in an Outfit folder.

2) You wait for colors to appear. This version extracts all the outfits, so the import is much longer ; for testing purposes, delete all the outfit folders except one, it makes the import as quick as the stable version since it doesn't have more stuff to deal with.

3) Once the model is here, everything works like the previous version.
- You click "Prep for target application" and wait for it to merge the meshes and do other stuff.
- Then you select the Body mesh and click "Bake material templates", choose a folder, and wait for it to create the textures in that folder.
- Then you click "Apply baked templates" and choose the folder where you stored the textures.

4) Finally, go in CATS tab. Create the atlas materials, the VIseme to get face expressions, and once you're done, export the model with the CATS Export button.

That's the theory. It's basically like version 5.0.2, except the Import process takes a single click. Those buttons disappeared because they're done automatically now.

This version worked for me for a little while ; I had even modified the code for it to extract the model without separating the meshes. But then I updated Koikatsu, and I'm pretty sure that messed up the plugin, so in practice, this version may not be stable enough to export models.
