### ISSUE TITLE
HoneySelect 2 / HS2 support?

### ISSUE THREAD

**Issue by RandomBagel** [FlailingFog/KK-Blender-Porter-Pack#213]
Hey, I'm looking for an easy way to export models from HS2. Since that game and KK look to be very similar under the hood, I was wondering if this was planned/possible?

(or tell me an alternative if i'm being dumb)

**Comment by poisenbery** [comment]
I've actually looked into this. Most of the code would need to be re-written specifically for HS2.
T posing is much more difficult in HS2 because the poses are not named like they are in KK/KKS.

The texture mapping techniques are also undoubtable different, which means the blender side of the plugin would also have to be completely re-written.

**Comment by LocalVoidwalker** [comment]
im also interested in this. have you made any progress on it?

**Comment by FlailingFog** [comment]
It isn't planned for this project, but you can try SKLX creator, that's the only thing I'm aware of that supports exporting HS2 models.
