### ISSUE TITLE
Rigify Script Armature does not affect the model itself

### ISSUE THREAD

**Issue by PizzamanArgox** [FlailingFog/KK-Blender-Porter-Pack#247]
I am editing this thread because my old issue was my mistake, sorry about it. 

Anyways after running the rigify script, it seems that the new generated armature(rigify armature) is not so different than the previous one and it does not affect the model in anyway meaning I cant pose it for some reason. It doesnt seem like rigify armature(except for some parts) as well
![image](https://user-images.githubusercontent.com/108461687/190040899-44c45a4e-7585-4afa-a6c7-4d70e66d8a92.png)

**Comment by ilcane87** [comment]
Hi @PizzamanArgox, do you get the same issue with any character, or just the one in the picture?
If it's the latter, could you post the character card?

If it's the former, there's probably something wrong in the way you go about it. For example, remember that you have to click the Rigify star-shaped button twice, the first time to get the 'metarig', and the second time to actually convert it to the typical Rigify control rig.
And finally, you have to parent the new armature to all objects (body, clothes, hair, etc...) with empty groups.
See this comment for a more detailed checklist: https://github.com/FlailingFog/KK-Blender-Porter-Pack/issues/78#issuecomment-1032952719

Also, check your log for errors that might be preventing the script from performing all operations.

**Comment by PizzamanArgox** [comment]
Hello @ilcane87 , first of all I really would like to thank you for helping me
I tried it with another character just now, result is the same. Rig doesnt control anything. I'm thinking maybe there's something I'm missing or skipping in the way I do it, so for that reason I'm writing how I'm doing it;
1- I import the PMX file from Blender's own Import section, not CATS plugin's
2- Using the KKBP, I "Finalize PMX File"
3- After the finalization is done, I separate the Hair and name them "Hair"
4- After that, I Import the KK Shader and Textures, that gets followed by "Convert and Apply" task
5- I did not do tasks 3-5 in KKBP(prep for target application, bake materails, apply baked materails) however if I'm correct doing the prep for target application task doesnt let me import the files into Unreal Engine (something about being more than one root bones), so I skipped them in this one
6- I click on Convert for Rigify, wait for it to be done, then click it again and see the rig appear
7- I parent the objects to rig using CTRL + P
Result is the same, rig doesnt control model, please let me know if I'm doing something wrong or I'm missing something. Thank you and I'm sorry if it's something I did wrong
![image](https://user-images.githubusercontent.com/108461687/190114271-b51e7fc3-b68b-42a1-a186-87b8244e3c55.png)

**Comment by ilcane87** [comment]
Your procedure is entirely correct except for step 1: using CATS is not optional, you'll get different results if you import with Blender's native function.
For example a few months ago someone who was doing the same thing also couldn't get Rigify to work correctly, and it turned out that the way Blender imports the skirt bones was making them disconnected, while the Rigify conversion plugin expects them to be connected, otherwise it will interrupt the operations halfway through, resulting in a half-converted rig like the one from your image.
I'm sure that if you checked the console logs after trying the Rigify conversion, you'd see the error.

One more thing: in Step 7 you mention using Ctrl+P to parent, and I assume you mean that you aren't picking the empty groups option, but just doing basic parenting; while that is not entirely wrong, that operation does not create a new Armature constraint for your objects, so that would still result in your rig not deforming them.
So you can either use standard parenting and then manually modify the existing Armature constraint in each object to target the new generated rig instead of the metarig, or just do as instructed before and use the 'Parent with empty groups' option.

**Comment by PizzamanArgox** [comment]
Thank you, that was the problem, I actually never thought that would make a difference since I did not use that few months back when I was working with Koikatsu Models
