### ISSUE TITLE
Keep original bone structure.

### ISSUE THREAD

**Issue by MediaMoots** [FlailingFog/KK-Blender-Porter-Pack#29]
As you may have noticed, the current workflow (PMX and CATS) completely nukes the original bone structure, making retargeting animations taken from Koikatsu very time consuming.

One workflow I used was to, use the PMX model, not fix the bones through CATS and manually delete all the extra bones (while comparing the bone structure to GME's fbx export)

This works well but takes an awfully long time.

Since GMEs armature has issues with scale, we also can't use the exported fbx.

Any ideas?
Thanks.

**Comment by FlailingFog** [comment]
Looking back, I kind of forgot what is gained by using CATS to fix the model... I've always it used as part of the process because it nicely connects the main bones together but like you said, using it at all wrecks the bone structure. It'd probably be easy to copy their code to do **just** the bone connections, and if that were done then I think CATS could be dropped and the armature could be preserved to match the one in koikatsu. 

Though, now that this plugin advertises CATS export compatibility + Unity compatibility, I'd have to check what exactly CATS does so nothing is broken by **not** using it.  

(Also, I'm looking into using the fbx files now, even with the scaling issues. I was originally going to make the fbx files match the pmx files then send it through CATS, but maybe this could be a good opportunity to move away from CATS instead...)

**Comment by MediaMoots** [comment]
`It'd probably be easy to copy their code to do just the bone connections, and if that were done then I think CATS could be dropped and the armature could be preserved to match the one in koikatsu. Though, now that this plugin advertises CATS export compatibility + Unity compatibility, I'd have to check what exactly CATS does so nothing is broken by not using it.`

What sort of bone connection/correction does it (CATS) do?

One idea I had for a scripted workflow is this:
1. Import the PMX model
2. Import and get a list of bones from GME's FBX
3. Rename some bones manually (scripted) in the PMX model to match GME (Such as 上半身 -> cf_j_spine01)
4. Get the list from earlier and iterate through PMX's bones, deleting the ones not in the list.
5. Profit (I think, haha)

This workflow would remove the need for CATS aside from importing and exporting (which works flawlessly with the workflow from my original comment).

Is there anything else that CATS is necessary for?
![image](https://user-images.githubusercontent.com/81146974/130350114-5db5751a-722f-4fbc-b6ac-dcfd6c803b25.png)
Even disabling all the options here, renames all bones and structure.

**Comment by MediaMoots** [comment]
More info.

GME root bone vs KK animation root bone

GME:
![image](https://user-images.githubusercontent.com/81146974/130351506-406c8aea-fc49-4f5c-bd9d-7368ada926ce.png)

KK:
![image](https://user-images.githubusercontent.com/81146974/130351516-71ef0273-5d06-4d15-9d65-595182a92be4.png)


Note the extra `BodyTop` bone and the different naming of the `p_cf_body_bone`

**Comment by MediaMoots** [comment]
Conversion list.
(It should all be correct, if not please let me know)

Source:
全ての親
センター
上半身
上半身2
左AH1
左AH2
右AH1
右AH2
左肩
左腕
左ひじ
左手首
左人指１
左人指２
左人指３
左小指１
左小指２
左小指３
左中指１
左中指２
左中指３
左薬指１
左薬指２
左薬指３
左親指０
左親指１
左親指２
右肩
右腕
右ひじ
右手首
右人指１
右人指２
右人指３
右小指１
右小指２
右小指３
右中指１
右中指２
右中指３
右薬指１
右薬指２
右薬指３
右親指０
右親指１
右親指２
首
頭
両目x
_dummy_左目x
_dummy_右目x
左目x
右目x
_shadow_左目x
_shadow_右目x
胸親
左胸操作
右胸操作
下半身
左足
左ひざ
左足首
左つま先
右足
右ひざ
右足首
右つま先
左足ＩＫ
左つま先ＩＫ
右足ＩＫ
右つま先ＩＫ

Converted:
X
X
cf_j_spine01
cf_j_spine02
cf_j_bust02_L
X
cf_j_bust02_R
X
cf_d_shoulder02_L
cf_j_arm00_L
cf_j_forearm01_L
cf_j_hand_L
cf_j_index01_L
cf_j_index02_L
cf_j_index03_L
cf_j_little01_L
cf_j_little02_L
cf_j_little03_L
cf_j_middle01_L
cf_j_middle02_L
cf_j_middle03_L
cf_j_ring01_L
cf_j_ring02_L
cf_j_ring03_L
cf_j_thumb01_L
cf_j_thumb02_L
cf_j_thumb03_L
cf_d_shoulder02_R
cf_j_arm00_R
cf_j_forearm01_R
cf_j_hand_R
cf_j_index01_R
cf_j_index02_R
cf_j_index03_R
cf_j_little01_R
cf_j_little02_R
cf_j_little03_R
cf_j_middle01_R
cf_j_middle02_R
cf_j_middle03_R
cf_j_ring01_R
cf_j_ring02_R
cf_j_ring03_R
cf_j_thumb01_R
cf_j_thumb02_R
cf_j_thumb03_R
cf_j_neck
cf_j_head
X
X
X
cf_J_hitomi_tx_L
cf_J_hitomi_tx_R
X
X
X
X
X
cf_j_waist01
cf_j_thigh00_L
cf_j_leg01_L
cf_j_foot_L
X
cf_j_thigh00_R
cf_j_leg01_R
cf_j_foot_R
X
X
X
X
X

(`X` means: Can be removed)

Both of the cf_j_foot_(L/R) bones need to be reparented to cf_j_leg03_(L/R)

**Comment by MediaMoots** [comment]
Here's a script that does all the above.

All you need to do is:
1. Import the PMX model through CATS with the following settings
![image](https://user-images.githubusercontent.com/81146974/130357636-bce1a720-b395-42d8-9374-139d39cf66d9.png)

2. Import the FBX model from GME
3. Run the script
4. Profit

```
import re
import bpy
import fnmatch

pmx = bpy.data.objects['Model_arm']
gme = bpy.data.objects['Armature']

pmxCJKBoneNames = ["全ての親","センター","上半身","上半身2","左AH1","左AH2","右AH1","右AH2","左肩","左腕","左ひじ","左手首","左人指１","左人指２","左人指３","左小指１","左小指２","左小指３","左中指１","左中指２","左中指３","左薬指１","左薬指２","左薬指３","左親指０","左親指１","左親指２","右肩","右腕","右ひじ","右手首","右人指１","右人指２","右人指３","右小指１","右小指２","右小指３","右中指１","右中指２","右中指３","右薬指１","右薬指２","右薬指３","右親指０","右親指１","右親指２","首","頭","両目x","_dummy_左目x","_dummy_右目x","左目x","右目x","_shadow_左目x","_shadow_右目x","胸親","左胸操作","右胸操作","下半身","左足","左ひざ","左足首","左つま先","右足","右ひざ","右足首","右つま先","左足ＩＫ","左つま先ＩＫ","右足ＩＫ","右つま先ＩＫ"]
gmeCJKBoneNames = ["X","X","cf_j_spine01","cf_j_spine02","cf_j_bust02_L","X","cf_j_bust02_R","X","cf_d_shoulder02_L","cf_j_arm00_L","cf_j_forearm01_L","cf_j_hand_L","cf_j_index01_L","cf_j_index02_L","cf_j_index03_L","cf_j_little01_L","cf_j_little02_L","cf_j_little03_L","cf_j_middle01_L","cf_j_middle02_L","cf_j_middle03_L","cf_j_ring01_L","cf_j_ring02_L","cf_j_ring03_L","cf_j_thumb01_L","cf_j_thumb02_L","cf_j_thumb03_L","cf_d_shoulder02_R","cf_j_arm00_R","cf_j_forearm01_R","cf_j_hand_R","cf_j_index01_R","cf_j_index02_R","cf_j_index03_R","cf_j_little01_R","cf_j_little02_R","cf_j_little03_R","cf_j_middle01_R","cf_j_middle02_R","cf_j_middle03_R","cf_j_ring01_R","cf_j_ring02_R","cf_j_ring03_R","cf_j_thumb01_R","cf_j_thumb02_R","cf_j_thumb03_R","cf_j_neck","cf_j_head","X","X","X","cf_J_hitomi_tx_L","cf_J_hitomi_tx_R","X","X","X","X","X","cf_j_waist01","cf_j_thigh00_L","cf_j_leg01_L","cf_j_foot_L","X","cf_j_thigh00_R","cf_j_leg01_R","cf_j_foot_R","X","X","X","X","X"]

gmeBoneList = []

# Rename the root bone from p_cf_body_bone to p_cf_body_00
fixModelForKK = True

# First remove all constraints from PMX
for poseBone in pmx.pose.bones:
    for c in poseBone.constraints:
        poseBone.constraints.remove(c)
   
# Then rename PMX bones
for pmxBone in pmx.data.bones:
    if pmxBone.name in pmxCJKBoneNames:
        for idx, pmxBoneName in enumerate(pmxCJKBoneNames):
            if fnmatch.fnmatchcase(pmxBone.name, pmxBoneName):
                if not gmeCJKBoneNames[idx] == 'X':
                    pmxBone.name = gmeCJKBoneNames[idx]
                    break
                
# Prepare a list of bones from GME
for bone in gme.data.bones:
    gmeBoneList.append(bone.name)

# Ensure PMX is selected then enable Edit Mode
pmx.select = True
bpy.ops.object.mode_set(mode='EDIT')

# Remove bones that GME doesn't have from PMX
for editBone in pmx.data.edit_bones:
    if not editBone.name in gmeBoneList:
        pmx.data.edit_bones.remove(editBone)

# Reparent feet bones
pmx.data.edit_bones['cf_j_foot_L'].parent = pmx.data.edit_bones['cf_j_leg03_L']
pmx.data.edit_bones['cf_j_foot_R'].parent = pmx.data.edit_bones['cf_j_leg03_R']

# Renames the root bone to be compatible with KK animations
if fixModelForKK:
    pmx.data.bones['p_cf_body_bone'].name = 'p_cf_body_00'
    pmx.data.edit_bones.remove(pmx.data.edit_bones['BodyTop'])

# Disable Edit Mode for PMX
bpy.ops.object.mode_set(mode='OBJECT')

```

**Comment by FlailingFog** [comment]
Thanks for this info! I took a slightly different route: https://github.com/FlailingFog/KK-Blender-Shader-Pack/blob/V5-merger/importing/finalizepmx.py
If you import the pmx file using the "Import Model" button in CATS (not the hamburger menu) then run this script, it'll...
* Rename the bones to match the fbx armature
* Rotate the finger bones to match the fbx file
* Reset the leg / foot bone orientation to match the fbx file
* Set the bone roll to match a dump from a reference fbx file (the animations didn't seem to work until I did this)
    * The finger rolls still need corrections
* **Rename the bones a second time** to match the output of CATS's fix model button
* Set the bone order to be cf_n_height > cf_j_hips (skipped the other bones since they don't seem to contain animation data)
* Reparents the foot
* Delete some of the useless bones. You can't delete all of the bones because some accessories have pmx armature bones that don't appear on the fbx armature (these are the accessories that have the scaling issue).

Then I imported the fbx animation, selected the pmx armature, then shift selected the fbx animation armature and ran this: https://github.com/FlailingFog/KK-Blender-Shader-Pack/blob/V5-merger/extras/importanimation.py
This one...
* **Renames the bones in the fbx animation armature** to match the names of the CATS output
* Makes the bone order edits to match the edits in the previous script
* Copies the animation from the active object (animation armature) to the selected object (pmx armature)

I forgot I make additional armature edits during the bonedrivers.py script, so that's another thing that could break this

>What sort of bone connection/correction does it (CATS) do?

It visually connects bones together like fingers and skirt bones. And turns out it's accessible through an ops command: bpy.ops.cats_manual.connect_bones()
Unfortunately it breaks something with the animations, so I left it out.

**Comment by MediaMoots** [comment]
Quite good, there is one issue with the above workflow though.

How would it deal with many animations?

With the workflow I posted, you could retarget quickly using the rokoko plugin or even in engine (Unity/UE4) since all the names would match, thus removing the need to process KK animations in blender.
This is a big time saver, because there are hundreds of animations that can be exported from KK.


`Rename the bones a second time to match the output of CATS's fix model button`
I guess this keeps compatibility?

`Set the bone order to be cf_n_height > cf_j_hips (skipped the other bones since they don't seem to contain animation data)`
Simply curious, why does this need to be done, is it somehow separated, all my models have them connected correctly (PMX/GME)
Original PMX bones:
![image](https://user-images.githubusercontent.com/81146974/130376401-c7408fad-8613-46cd-bfd2-a910571d871a.png)

`Delete some of the useless bones. You can't delete all of the bones because some accessories have pmx armature bones that don't appear on the fbx armature (these are the accessories that have the scaling issue).`
Good catch, which bones are they?

**Comment by MediaMoots** [comment]
Here's V2 of my script.

Now it should keep all accessory bones that are in use, and instead of directly deleting the bones, it selects them and then you manually use CATS to merge them to parents.

```
import re
import bpy
import fnmatch

############################################################### CONFIG


# Rename the root bone from p_cf_body_bone to p_cf_body_00 and deletes extra roots
fixModelForKK = False


############################################################### PRIVATE


pmx = bpy.data.objects['Model_arm']
pmxBody = bpy.data.objects['Model_mesh']
gme = bpy.data.objects['ArmatureGMESchool']

pmxCJKBoneNames = ["全ての親","センター","上半身","上半身2","左AH1","左AH2","右AH1","右AH2","左肩","左腕","左ひじ","左手首","左人指１","左人指２","左人指３","左小指１","左小指２","左小指３","左中指１","左中指２","左中指３","左薬指１","左薬指２","左薬指３","左親指０","左親指１","左親指２","右肩","右腕","右ひじ","右手首","右人指１","右人指２","右人指３","右小指１","右小指２","右小指３","右中指１","右中指２","右中指３","右薬指１","右薬指２","右薬指３","右親指０","右親指１","右親指２","首","頭","両目x","_dummy_左目x","_dummy_右目x","左目x","右目x","_shadow_左目x","_shadow_右目x","胸親","左胸操作","右胸操作","下半身","左足","左ひざ","左足首","左つま先","右足","右ひざ","右足首","右つま先","左足ＩＫ","左つま先ＩＫ","右足ＩＫ","右つま先ＩＫ"]
gmeCJKBoneNames = ["X","X","cf_j_spine01","cf_j_spine02","cf_j_bust02_L","X","cf_j_bust02_R","X","cf_d_shoulder02_L","cf_j_arm00_L","cf_j_forearm01_L","cf_j_hand_L","cf_j_index01_L","cf_j_index02_L","cf_j_index03_L","cf_j_little01_L","cf_j_little02_L","cf_j_little03_L","cf_j_middle01_L","cf_j_middle02_L","cf_j_middle03_L","cf_j_ring01_L","cf_j_ring02_L","cf_j_ring03_L","cf_j_thumb01_L","cf_j_thumb02_L","cf_j_thumb03_L","cf_d_shoulder02_R","cf_j_arm00_R","cf_j_forearm01_R","cf_j_hand_R","cf_j_index01_R","cf_j_index02_R","cf_j_index03_R","cf_j_little01_R","cf_j_little02_R","cf_j_little03_R","cf_j_middle01_R","cf_j_middle02_R","cf_j_middle03_R","cf_j_ring01_R","cf_j_ring02_R","cf_j_ring03_R","cf_j_thumb01_R","cf_j_thumb02_R","cf_j_thumb03_R","cf_j_neck","cf_j_head","X","X","X","cf_J_hitomi_tx_L","cf_J_hitomi_tx_R","X","X","X","X","X","cf_j_waist01","cf_j_thigh00_L","cf_j_leg01_L","cf_j_foot_L","X","cf_j_thigh00_R","cf_j_leg01_R","cf_j_foot_R","X","X","X","X","X"]



############################################################### RENAME & CLEAN


# Rename PMX bones
for pmxBone in pmx.data.bones:
    if pmxBone.name in pmxCJKBoneNames:
        for idx, pmxBoneName in enumerate(pmxCJKBoneNames):
            if fnmatch.fnmatchcase(pmxBone.name, pmxBoneName):
                if not gmeCJKBoneNames[idx] == 'X':
                    pmxBone.name = gmeCJKBoneNames[idx]
                    break

# Remove all constraints from PMX
for poseBone in pmx.pose.bones:
    for c in poseBone.constraints:
        poseBone.constraints.remove(c)


############################################################### DATA COLLECTION


### Function to check for empty vertex groups
def survey(obj):
    maxWeight = {}
    for i in obj.vertex_groups:
        maxWeight[i.index] = 0

    for v in obj.data.vertices:
        for g in v.groups:
            gn = g.group
            w = obj.vertex_groups[g.group].weight(v.index)
            if (maxWeight.get(gn) is None or w>maxWeight[gn]):
                maxWeight[gn] = w
    return maxWeight

# Find empty vertex groups
vertexWeightMap = survey(pmxBody)
vertexIndexes = []
vertexIndexes.extend(vertexWeightMap.keys())
vertexIndexes.sort(key=lambda gn: -gn)

# Prepare a list of vertex group names
vertexGroupNames = []
for vg in pmxBody.vertex_groups:
    vertexGroupNames.append(vg.name)
    

# Prepare a list of bones from GME
gmeBoneList = []
for bone in gme.data.bones:
    gmeBoneList.append(bone.name)


############################################################### SELECT BONES


# Ensure that only the PMX is selected then enable Edit Mode
bpy.ops.object.mode_set(mode='OBJECT')
bpy.ops.object.select_all(action='DESELECT')
pmx.select = True
bpy.ops.object.mode_set(mode='EDIT')



# First, delete the bones that are not in vertex groups (For some reason CATS does not remove them when merging weights)
for editBone in pmx.data.edit_bones:
    if not editBone.name in vertexGroupNames:
        pmx.data.edit_bones.remove(editBone)

# Then, select the bones that have empty vertex groups and are not in GME
for idx in vertexIndexes:  
    vg = pmxBody.vertex_groups[idx]
    if vertexWeightMap[idx]<=0 and vg.name not in gmeBoneList:
        print(vg.name)
        pmx.data.edit_bones[vg.name].select = True

##### Finally, manually use CATS to merge weights to parents


############################################################### FINAL CLEANUP


# Reparent feet bones
pmx.data.edit_bones['cf_j_foot_L'].parent = pmx.data.edit_bones['cf_j_leg03_L']
pmx.data.edit_bones['cf_j_foot_R'].parent = pmx.data.edit_bones['cf_j_leg03_R']

# Changes the root bone to be compatible with KK animations (Needs to be run after CATS)
if fixModelForKK:
    pmx.data.bones['p_cf_body_bone'].name = 'p_cf_body_00'
    pmx.data.edit_bones.remove(pmx.data.edit_bones['BodyTop'])
    pmx.data.edit_bones.remove(pmx.data.edit_bones['全ての親'])
```

**Comment by FlailingFog** [comment]
> Here's V2 of my script.

That could work!
> I guess this keeps compatibility?

I have no idea. I just assumed CATS renames the bones so they can be automatically detected in Unity. I haven't tried importing the model without the renamed bones to see what it does. I also think bone names like 'Hips' rather than 'cf_j_hips' are easier to identify

> Simply curious, why does this need to be done

They're connected correctly on mine too, and it doesn't need to be done. I just think it makes for a slightly cleaner armature, even if it deviates from the KK armature structure (one center bone instead of multiple).

> Good catch, which bones are they?

The ca_slot bones

> With the workflow I posted, you could retarget quickly using the rokoko plugin or even in engine (Unity/UE4) since all the names would match, thus removing the need to process KK animations in blender.

Interesting! I didn't know that was possible. Though, I want a specific setup for use inside of blender and the animations would still need to be edited with that specific setup. I want a way to add IKs to the arms to use for non-premade animations and the only way I've found to do it is to connect the tail of the arm bone to the head of the hand bone. This reorients the bone, so the animations for those bones have to be reoriented as well. I guess I consider this another reason to not worry about changing the armature structure, since this setup would require code to get the animations to work anyway.
I was able to reorient the animations in line 105 of [the script from earlier](https://github.com/FlailingFog/KK-Blender-Shader-Pack/blob/V5-merger/extras/importanimation.py) to make the fbx animations compatible with this change.  Not sure how the rokoko plugin handles the reoriented bone issue, but if it does it automagically then that might be easier. 

Another thought: What if there were two configurations you could choose from?
* One for the original armature that kept the original bone names/structure and didn't have IKs, but was fully compatible with the fbx animations inside and outside of blender
* One with the slightly modified armature that did have IKs and friendlier bones, but you'd have to run the piece of code to use fbx animations inside of blender, and could run another piece of code to swap back to the original armature at any time and regain that compatibility

**Comment by MediaMoots** [comment]
> What if there were two configurations you could choose from?

That would be perfect, haha

**Comment by MediaMoots** [comment]
So, made a script to batch retarget all Armature animations in the `Source` collection to the Armature in the `Target` collection.
I'm not sure if this fits in this addon, but just wanted to share.


```
import bpy

targetCollection = bpy.data.collections['Target']
targetArmature = targetCollection.objects['Armature']

sourceCollection = bpy.data.collections['Source']
sourceArmatures = sourceCollection.objects

for src in sourceArmatures:
    try:
        if src.type == 'ARMATURE':
            bpy.data.scenes["Scene"].rsl_retargeting_armature_target = targetArmature
            bpy.data.scenes["Scene"].rsl_retargeting_armature_source = src
            bpy.ops.rsl.build_bone_list()
            bpy.ops.rsl.retarget_animation()
    except:
        print('Error')
        pass
```

**Comment by FlailingFog** [comment]
I don't see why it couldn't be added. I can put it in as a toggle.

**Comment by FlailingFog** [comment]
Most of this is in the latest commit, so you can try it if you want.
* Use the big import button in CATS to import the pmx file
* open the KKBP sidebar
* expand the Import options (fbx and pmx) panel
* Uncheck the "Use modified armature" toggle
* click 1a) FInalize pmx button
* expand the Extras panel
* click the Import ripped fbx button and choose the ripped fbx file (make sure it's the cf_body_00 type or the "center" bone won't move)

I haven't installed the rokoko plugin yet so I don't know if the toggle works

Haven't put in the "survey" code for removing the useless pmx bones yet, right now it just removes the k_f_ bones and the cf_hit bones that the pmx armature comes with. There's a dictionary with the fbx bone names in finalizepmx.py so I think I'm going to use that instead of importing the fbx armature to generate the bone list.

If you load another animation in it'll overwrite the current one
Switching armature types (stock vs modified) after loading an animation currently breaks the animation

You can switch between the two armature types, but going from modified to stock will just mute the IK/joint drivers and stow the extra (modified) bones created during bonedrivers.py under the pv_root_bone. Do those extra bones matter when retargeting animations with other software (rokoko/unity/unreal)? If it doesn't, then I'll probably keep that behaviour because it makes it easier to switch

**Comment by MediaMoots** [comment]
> click the Import ripped fbx button and choose the ripped fbx file (make sure it's the cf_body_00 type or the "center" bone won't move)

GME's fbx?

> If you load another animation in it'll overwrite the current one

Hmm, I'm not sure using KKBP to import animations is really that useful (For me anyway, since I need to convert many animations)
All KKBP needs to do (imo) is to preserve the stock skeleton perfectly so that it can be retargeted easily.

What do you think?

**Comment by FlailingFog** [comment]
> GME's fbx?

The ripped fbx animations from \Koikatsu\abdata\action\animator\

> All KKBP needs to do (imo) is to preserve the stock skeleton perfectly so that it can be retargeted easily.

That's fair, and if you uncheck the modify armature toggle then it'll preserve everything. 
I just made it such that the Import fbx button will import the fbx animation file (without processing it) and send it through the rokoko code you put above, but maybe I misunderstood the usage.

**Comment by MediaMoots** [comment]
I think the way it works now is good.

If you had included the "survey" code to remove unused bones, the naming scheme of separate characters (after export) would be different.

As it is now (I think, needs testing) every character that goes through KKBP will have the same bone structure, and that, I feel, is a good thing, because it makes creating multiple characters in Unity/UE4 easier, e.g. no need to code for separate skeletons.

**Comment by MediaMoots** [comment]
On an unrelated note, do you know how to solve this sort of issue?
![image](https://user-images.githubusercontent.com/81146974/133414011-8fb5f53a-6f16-4c5a-999e-53fcbf25d625.png)
The hair not being in the right place.
This is the card:
![Koikatu_F_20210824140538769_Tempest_Rimiru_ROHss](https://user-images.githubusercontent.com/81146974/133414213-f3b86761-35db-4698-b9fc-db18e23d73f7.png)

Thanks.

**Comment by FlailingFog** [comment]
>I think the way it works now is good.

Okay I'll leave it as is then. If needed later it can be added as a toggle

**Comment by MediaMoots** [comment]
These bones are different from the KK base skeleton.

![image](https://user-images.githubusercontent.com/81146974/135703539-985aea1a-3f48-4abd-89a8-fdf314c48308.png)

**Comment by MediaMoots** [comment]
If you want, I could make the new KKBP_Exporter plugin to not add these extra bones and change bone names.
So, no more Japanese bone names/extra bones (AH, etc...) in the pmx.
Would that be helpful?

**Comment by MediaMoots** [comment]
All right, I made changes to the plugin, now it exports the rig 1 to 1 (no extra physics/ik/renamed bones)
Feel free to test it.
If you end up using it then I'll include the plugin (With the bone export edit) in PR #43 

[KKBP_Exporter_dev.zip](https://github.com/FlailingFog/KK-Blender-Shader-Pack/files/7270877/KKBP_Exporter_dev.zip)

**Comment by MediaMoots** [comment]
Bug fix
[KKBP_Exporter.zip](https://github.com/FlailingFog/KK-Blender-Shader-Pack/files/7270916/KKBP_Exporter.zip)

**Comment by MediaMoots** [comment]
> As it is now (I think, needs testing) every character that goes through KKBP will have the same bone structure, and that, I feel, is a good thing, because it makes creating multiple characters in Unity/UE4 easier, e.g. no need to code for separate skeletons.

After more testing, i found that this is incorrect.
There's no benefit in keeping the unused bones for retargeting in UE4.

So maybe it would be good to either use the survey code to delete unused bones during finalize pmx or have the survey/unused bones removal script as a button in the extras section.

**Comment by FlailingFog** [comment]
Having the original bone structure would help, I'd just have to redo some parts during the finalize step.
The unused / intermediate bones are stored on armature layer 11, so if you select the bones on that layer and use the merge weights thing in CATS it should work the same.

**Comment by MediaMoots** [comment]
@FlailingFog 
Ok so, after messing around with the skeleton, I found out that these bones are useful for IK
![image](https://user-images.githubusercontent.com/81146974/136730463-9b111aa1-3472-4c29-8722-d67f82f20149.png)

So would it be possible to keep them?
Thanks!

**Comment by MediaMoots** [comment]
Also found a bug with the hair select
![image](https://user-images.githubusercontent.com/81146974/136731027-743e490a-3b58-4935-84f3-4ea520b1f02a.png)
It seems that subtracting 1 from the len causes the script to not select the last material in the list, thus giving this result:
![image](https://user-images.githubusercontent.com/81146974/136731089-74fc9096-7a0a-4e19-b513-07b00e84626a.png)

Using this:
![image](https://user-images.githubusercontent.com/81146974/136731108-8854ddd2-2ad3-4809-bf84-217356797e3e.png)

Produces the correct result:
![image](https://user-images.githubusercontent.com/81146974/136731126-dc889fd2-84a8-40ac-88a6-7257d67593f2.png)

**Comment by FlailingFog** [comment]
Thanks for finding these. The hit/kf bones are on armature layers 12 and 13 now

**Comment by FlailingFog** [comment]
It shouldn't do that anymore.

And semi-related to this, sometimes the original pmx exporter creates a model with broken tongue and lower teeth shapekeys (kuti_sita and kuti_ha). This bug carried over into your new version as well. It only happens on certain cards (like that megumin card from a while back) and I haven't noticed a trend for what causes it. Since you have the source, do you happen to know what could cause it to break _only_ those shapekeys like that?

**Comment by FlailingFog** [comment]
>I just removed part of the code that the original plugin used to manually modify shape keys, now it should have only the original keys from KK.

Are the shapekey names supposed to change with this too? I'm still seeing the original ones

**Comment by MediaMoots** [comment]
Ah, pity, I'll investigate this issue more.

**Comment by FlailingFog** [comment]
I've been trying to work the duplicate vertex group issue, and after looking into it a little further I think the KK pmx exporter is the one causing the vertex groups to merge, not Blender's pmx importer. When I take the pmx file into another program (PMXEditor) it's showing that the vertex groups are already merged. 

I feel like this would resolve itself if the KKBP exporter didn't merge all the objects into one like it usually does, and instead kept everything in separate objects, similar to how Grey's mesh exporter does it. Is this an easy thing to do? I'm guessing the pmx exporter merges the meshes at some point, so would it be as simple as deleting that chunk of code?

I'll continue trying to get it to work with the code I have now, but so far the trick I'm using isn't completely cutting it for dense groups of accessories (like when people make hair completely out of accessories).

**Comment by MediaMoots** [comment]
Ok, yeah, I think I found a bug in the plugin, I'll try and fix it.

**Comment by MediaMoots** [comment]
![image](https://user-images.githubusercontent.com/81146974/140650429-aa8a6a6a-2a4e-46f2-b593-949130d41a8e.png)
**: )**

**Comment by MediaMoots** [comment]
> ![image](https://user-images.githubusercontent.com/81146974/140650429-aa8a6a6a-2a4e-46f2-b593-949130d41a8e.png) **: )**

PR #61

**Comment by MediaMoots** [comment]
V5 is great, thanks!
