### ISSUE TITLE
Inverse Kinematics not properly aligned

### ISSUE THREAD

**Issue by poisenbery** [FlailingFog/KK-Blender-Porter-Pack#308]
![Screenshot (1036)](https://user-images.githubusercontent.com/78466408/200404768-87a1d11f-59ca-44b1-bbb3-8e04c9870c13.png)
![Screenshot (1037)](https://user-images.githubusercontent.com/78466408/200404771-c1a36e70-30f7-4421-b8bd-4d214c7391f3.png)

Elbow bone pops out with the KK Armature. Transfers over to Rigify if used.
Causes different deforms.

I noticed that Left/Right Arm bones diverge from where they actually should be. Not entirely sure if this is the cause, but it's the only one I can think of.

**Comment by poisenbery** [comment]
![Screenshot (1042)](https://user-images.githubusercontent.com/78466408/200407229-b6ab7631-0056-46c3-bbd1-972aee70faca.png)
![Screenshot (1043)](https://user-images.githubusercontent.com/78466408/200407235-1f0f33bb-f7d0-44c8-a312-0871c672ab4f.png)
So, before movement, the bones are perfectly aligned, but after movement, you can see that there is a divergence.

**Comment by ilcane87** [comment]
Hi @poisenbery, I'm not sure if I understand what the problem is, but I can explain why the bone head seems to pop out of the arm.
There are some drivers that automatically adjust the deformation of the elbow based on how you rotate the forearm, and they act the same way in IK and FK mode. Two of those drivers affect the "cf_s_elboback_L" bone, that you can see in the picture below:

![Scene](https://user-images.githubusercontent.com/34897042/200572612-59e93348-b935-4489-ba43-44ff9d19b0f7.png)

The right side shows what happens if you delete the drivers and then make the same movement, in that case the elbow bone you mentioned  stays right in the center of the mesh since it isn't modified by the drivers anymore, but the deformation looks much worse as a consequence.

By the way, there are also similar adjustment drivers acting for the shoulders, arms, wrists, waist, legs and knees deformations.

**Comment by poisenbery** [comment]
@ilcane87 Ahhhhh this makes sense. So if I remove those drivers, the bones won't shift anymore? 

> deformation looks much worse as a consequence.

I'm actually using X-Muscle System addon to solve that on my end. 
![flex](https://user-images.githubusercontent.com/78466408/200701281-a6177b83-5d22-46d5-bca7-79dce66e3e34.gif)

**Comment by poisenbery** [comment]
Awesome. I removed the drivers and it behaves the way I want. Thank you for the information!
![Screenshot (1045)](https://user-images.githubusercontent.com/78466408/200710664-bbdbbd4f-96ab-47c7-9060-b0d852723a55.png)
