### ISSUE TITLE
Applying vmd motion

### ISSUE THREAD

**Issue by vaimd** [FlailingFog/KK-Blender-Porter-Pack#314]
Hi,
I'm trying to apply vmd dance motion to model in blender.
but it's showing weird moving. Model moves freely right left, up and down... , and lower body isn't dancing.
Is there any way to apply vmd motion in blender ?
I would be happy if you could write workaround, or something right settings.

tried with KKS, KKBP_Exporter_V3.98, mmd_tools-v2.8.0, blender 3.3

**Comment by ilcane87** [comment]
Hi @vaimd, it is definitely possible to use VMD motions for these models, but I don't think you can easily get satisfying results by just applying them directly, since there may be differences in the rest pose, axes, IK handling, etc...

What I usually do instead is using retargeting tools that take care of most of the tricky stuff automatically, I recommend you to check out this playlist, especially the video about the free Rokoko addon:
https://www.youtube.com/playlist?list=PLdcL5aF8ZcJux9f5Bvb1QlByiHWTK3ICP

I would advise you to retarget the motions in FK mode, it's going to be much easier and more accurate, and if you were to use the Rigify armature you can then automatically convert them to IK as needed, though whether that's a good idea or not depends on what you want to do with the animated model afterwards.

**Comment by vaimd** [comment]
it seems it is not easy to use vmd.
(I used MMD Director. but I want to make animation in Blender now)

I hope import type PMX will allow to apply vmd motion.
I believe many people want to use huge assets easily.

@ilcane87
Thank you for your advice!
I didn't understand what import type is better. now I'm trying with Rokoko and with using import type "Rigify".
