### ISSUE TITLE
hip/pelvis bone positioning issue

### ISSUE THREAD

**Issue by naminode** [FlailingFog/KK-Blender-Porter-Pack#32]
Waist or hip warping happen for vrm format in most application. Seems fine on vrm viewer. 
![20210906012214_1](https://user-images.githubusercontent.com/88361811/132136084-ac134626-bf21-4cde-92a9-fe1c916dd390.jpg)
 ![image](https://user-images.githubusercontent.com/88361811/132136001-35b5a025-229c-4cc1-bf6c-ec55a9c34266.png)

**Comment by naminode** [comment]
Turns out the pelvis and hip bone are upside down.

**Comment by FlailingFog** [comment]
Shoot yeah, I just checked another model before and after V4.3.1 and see what you mean. I'm guessing it works correctly if you re-export after turning the bones the correct orientation in Blender? 

I didn't really look into what's causing it, but if that fixes it then this shouldn't be a problem when V5 is released because that version will have all of the bones facing upward.

**Comment by FlailingFog** [comment]
I tried V5 out in virtualcast and Vseeface and both had the hip upright, so I think this has been fixed
