### ISSUE TITLE
Multi Hair Color Support

### ISSUE THREAD

**Issue by LegionInstaller** [FlailingFog/KK-Blender-Porter-Pack#323]
Since the KK Exporter (probably Idk) exports only 1 main hair color instead of sub hair colors, there is only one so
yeah

**Comment by MediaMoots** [comment]
KKBP Exporter exports all the colors for every material so one way to fix this issue is to separate the hair object with `Pause to Categorize`

In KK
![image](https://user-images.githubusercontent.com/81146974/208231202-990d22d0-78bc-40fc-a082-cf826a36297b.png)

Deselect
![image](https://user-images.githubusercontent.com/81146974/208231217-ca7e6d4c-dac3-4721-bd38-90a8421b9dc3.png)

Result
![image](https://user-images.githubusercontent.com/81146974/208231237-b3825b0c-4857-471f-badf-cf5f73411490.png)

Because KKBP uses a special Hair shader for all hair objects, for now, only one hair color is supported when not separating manually.
