### ISSUE TITLE
Bake Material error

### ISSUE THREAD

**Issue by Si022** [FlailingFog/KK-Blender-Porter-Pack#327]
Model turns into a grey blob looses all textures & the following error is output into consol. Re-installed addon, same result with multiple cards. 

Traceback (most recent call last):
  File "C:\Users\xxxxx\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\KK-Blender-Porter-Pack-master\exporting\bakematerials.py", line 431, in execute
    setup_geometry_nodes_and_fillerplane(camera)
  File "C:\Users\xxxxx\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\KK-Blender-Porter-Pack-master\exporting\bakematerials.py", line 149, in setup_geometry_nodes_and_fillerplane
    links.new(group.outputs[0], output.inputs[0])
IndexError: bpy_prop_collection[index]: index 0 out of range, size 0

**Comment by BTHP5** [comment]
Sometimes you need to wait a little while for the textures to load. Otherwise, please make sure you're using Blender 3.3, and also that you're using the latest version of KKBP in Blender, and replace the exporter plugin in your Bepinex plugin folder.

You can check that you're using the right addon in blender by unchecking it in the addons tab, closing the tab, opening it again, installing the .zip file, waiting, then open the drop-down arrow under the addon name. That should tell you which version you're using. And then check the box next to the addon name.

**Comment by FlailingFog** [comment]
It looks like it's failing at the portion where it creates a geometry node group. There was a change with how a new geometry node group was created in Blender 3.2 so it might just be failing there because you're on 2.93.
Can you retry using Blender 3.3+?
