### ISSUE TITLE
When I import a model, the colours are weird.

### ISSUE THREAD

**Issue by BAP00tato** [FlailingFog/KK-Blender-Porter-Pack#331]
### this is my blender screenshot
![Untitled](https://user-images.githubusercontent.com/112852330/210497711-a70e99e7-9572-4d71-9a4d-25f2275b3c25.png)
_I noticed that her eyes are wide open, and blush seems less transparent_

### This is what my model looks like in game
![KoikatsuParty-2023-01-04-17-24-41-UI](https://user-images.githubusercontent.com/112852330/210497789-5537383c-aa90-422d-8f98-293115a60c5a.png)

### **_I'm new to using this so help would be appreciated._**

**Comment by johnvo0918** [comment]
I believe that KK has a shapekey value that applies on all model. When the model gets exported it doesn't take that value into consideration and gives you the default value, which is open wide, you can fix this just by playing with the shapekeys and saving it to default. 
Colors are weird because it's the most this plugin can do at the moment. Like the 3 [videos tutorial](https://www.youtube.com/watch?v=JSdggnGtcmU&list=PLhiuav2SCuvc-wbexi2vwSnVHnZFwkYNP&index=3) said, this plugin does 90% of the work and the last 10% is your own effort going inside the material shaders and tweak them yourself. 
the plugin makers can answer better than me though since this is what i've gathered on my own.
