### ISSUE TITLE
Can't import ripped .fbx animations

### ISSUE THREAD

**Issue by random356** [FlailingFog/KK-Blender-Porter-Pack#332]
I got this error after following the steps from:
https://www.youtube.com/watch?v=XFt12n7ByBI&t=465s

Python: Traceback (most recent call last):
  File "C:\Users\User\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\KK-Blender-Porter-Pack-621\extras\importanimation.py", line 88, in execute
    bpy.ops.import_scene.fbx(filepath=str(self.filepath), use_prepost_rot=False, global_scale=96)
  File "C:\Program Files\Blender Foundation\Blender 3.3\3.3\scripts\modules\bpy\ops.py", line 113, in __call__
    ret = _op_call(self.idname_py(), None, kw)
AttributeError: Calling operator "bpy.ops.import_scene.fbx" error, could not be found

I tried to use two imported .fbx files on 3 different imported models to no avail:

"f_talk_00_00_00-1-p_cf_body_00-0"
"Idle_08_01-0-p_cf_body_00-0"

Both animations where imported as FBX 2020_1.

![KK_238594](https://user-images.githubusercontent.com/32407939/210689401-29827491-25af-4848-9890-1a154a4d2c11.png)
![KK_105145](https://user-images.githubusercontent.com/32407939/210690198-8b959797-122a-4468-905a-4b1887d0db6e.png)

**Comment by FlailingFog** [comment]
I happened to look into this recently and found the following mostly works:
* import koikatsu model with the "Use Rigify Armature" option selected on the KKBP panel
* export .fbx animation from koikatsu data as shown in the video you linked (since then I've also noticed additional animations in /abdata/studio/anime/)
* import fbx file into blender through file menu on the top > import > fbx
* Retarget the fbx animation using the Rokoko addon shown here: https://www.youtube.com/watch?v=Nyxeb48mUfs&t=713s
* The naming is different from what is shown in the retargeting video. Import the Rokoko custom naming scheme using this json file: [chika.zip](https://github.com/FlailingFog/KK-Blender-Porter-Pack/files/10365322/chika.zip) , or by manually inputting all bones listed inside of the json file (open it in notepad)  

Some animations have bone location translations in addition to the rotations, but I don't know how to apply those using the Rokoko + Rigify combo so some animations will look slightly off

**Comment by random356** [comment]
Hey, thanks for the answer, while I'm able to partially import the animations into Blender (I did a small test) I'm kinda confused about how to translate bones since I'm still fairly new to Blender (i.e what kind of bone should cf_siri_L or k_f_kosi02_00 should be)
Any examples?

**Comment by FlailingFog** [comment]
If you're using the rokoko plugin you should be able to just load the .json file in the chika.zip above and it'll match up the bones automatically

**Comment by random356** [comment]
I forgot to say that I did indeed use the rokoko plugin to import the .json file into Blender, however, not all bones where translated.
 Also the animation I was trying to import was Idle_08_01-0-p_cf_body_bone-1
![Screenshot](https://user-images.githubusercontent.com/32407939/211225223-3e7d692b-af88-4b77-a807-cdf526a0bb89.png)
![Screenshot2](https://user-images.githubusercontent.com/32407939/211225224-0202f9b8-0e85-4d85-979a-76b78f61f852.png)

**Comment by FlailingFog** [comment]
fbx imports are mostly automated KKBP 6.4.0 now (including setting the bones up), so going to close
