### ISSUE TITLE
Error when baking

### ISSUE THREAD

**Issue by Sharaj00** [FlailingFog/KK-Blender-Porter-Pack#357]
Any card have this issue
![photo_2023-01-26_16-10-48](https://user-images.githubusercontent.com/16534883/214798431-00339d90-a39f-4ef0-9386-91d222325157.jpg)
Koikatsu BetterRepack RX16
Blender 3.4.1
KK Blender porter pack 6.4.0
CATS 0.19

**Comment by Sharaj00** [comment]
it was fixed when i have deleted tongue and other meshes what have been parented to body

**Comment by Sharaj00** [comment]
nah, again. previously i was trying to port model without clothing, but now(with clothing) i have same error

**Comment by Sharaj00** [comment]
baking clothes parts separately helps, but it much longer than all at once

**Comment by johnvo0918** [comment]
not alot of information i can use to help... maybe share the card and the viewport ?

**Comment by Sharaj00** [comment]
> not alot of information i can use to help... maybe share the card and the viewport ?
as i mentioned earlier, i have this issue with any card

**Comment by FlailingFog** [comment]
Do you happen to have another addon that affects the name or state of the Viewlayer? It looks like it's failing because one of the objects used for baking was placed on the wrong viewlayer.

You can also try the "absolute latest version" here to see if that fixes it: https://github.com/FlailingFog/KK-Blender-Porter-Pack#download

**Comment by Sharaj00** [comment]
> You can also try the "absolute latest version" here to see if that fixes it: https://github.com/FlailingFog/KK-Blender-Porter-Pack#download
now it works fine, thanks
