### ISSUE TITLE
Issue with rokoko and importing game animations on to characters. 

### ISSUE THREAD

**Issue by gomgom50** [FlailingFog/KK-Blender-Porter-Pack#360]
Strange bug when trying to use rokoko, right and left buttock handle seem to be getting animation data that is incorrect possibly due to some kind of incorrect mapping. This was attempted with the naming file included in the pluggin. 

https://imgur.com/a/k3q8MFS

gif ^ of the issue. 

This has been tried with several characters, animation is pulled from sunshine first then later from the original to see if sunshine was causing the issues but the problem remains. 

Instructions included in the animation library script were followed, both the 6.3 release and the latest git repo has been tried but the issue remains.

**Comment by FlailingFog** [comment]
You probably already noticed, but this should be fixed in the latest commit. It looks like the Rokoko addon retargets additional bones that are not on the naming file. Deleting all the animation data except for the bones on the naming file, as well as disabling certain rigify features (like neck and head follow) seemed to fix all skipping/corruption so far

**Comment by gomgom50** [comment]
Yes thank you! updating it solved the problem.
