### ISSUE TITLE
Bone Hierarchy Not correct for VRChat

### ISSUE THREAD

**Issue by Seiko-Senpai** [FlailingFog/KK-Blender-Porter-Pack#442]
So the bone Hierarchy when set to No Change and the VRChat Preset isnt actually supported in VRChat. The Simple and Very Simple structures work but it says it may cause issues with Full Body Tracking.
I will also say that I have not tested any other Armatures just the KKBP one so if i have to use one of them that's fine.

**Comment by FlailingFog** [comment]
The Upper Chest bone is deleted in the Simple / Very Simple VRChat selection because people have said it causes issues with eye tracking. Maybe full body tracking needs that bone? I'm not really familiar with it.
If you choose the VRM selection instead it will give you the same thing but the Upper Chest bone will be preserved.

Only the KKBP armature is supported when using the prep button.
