### ISSUE TITLE
Can you enable this plugin without installing the entire HF Patch?

### ISSUE THREAD

**Issue by NaughtDZ** [FlailingFog/KK-Blender-Porter-Pack#453]
I am using an integration package created by someone else, and the author himself has forgotten the version of HF Patch it uses. Downloading HFPatch again and installing it at the same time will confuse the plugins I have already installed. So, do I just need to extract the HF Patch section DLL file to make the plugin run smoothly?

In the current state, I  add KKBP_Exporter.dll in Koikatu\BepInEx\plugins,when start the game, the game will freeze the white screen for a period of time and then crash.

**Comment by FlailingFog** [comment]
I think you only need [the plugins listed here for it to work](https://github.com/FlailingFog/KK-Blender-Porter-Pack/blob/master/plugins/what%20is%20this.txt). It's just a lot easier to say to install the HF patch because it has all of these included. You also need whatever plugin/mod contains the T-pose according to https://github.com/FlailingFog/KK-Blender-Porter-Pack/issues/441

You should be able to check which plugins you already have by using the [KKManager program](https://github.com/IllusionMods/KKManager)
