### ISSUE TITLE
Optional Custom body mask problem

### ISSUE THREAD

**Issue by Diblox** [FlailingFog/KK-Blender-Porter-Pack#473]
Hello. I noticed the custom body mask is only a "additional color" node, and not how it was in the videos. The image for the optional custom body mask is nowhere to be found too.

![image](https://github.com/FlailingFog/KK-Blender-Porter-Pack/assets/11395821/e6eb75d6-a6d7-455d-9046-4d61ccdcc4a1)

This happens no matter the card used.

**Comment by FlailingFog** [comment]
That was the intended behaviour, it's supposed to give you a way to add additional transparency on top of the existing alphamask. You can change it from "additional only" to "either or" by changing the connections below. I'm also going to make this change in the actual shader since it does make more sense to do it that way.:
![image](https://github.com/FlailingFog/KK-Blender-Porter-Pack/assets/65811931/c52360d2-6ee9-46b8-b58b-fbd15e605c75)

Both the regular body mask and the optional body mask are located in the green texture group if you want to edit them:
![image](https://github.com/FlailingFog/KK-Blender-Porter-Pack/assets/65811931/8fc13dac-ad85-47f9-8316-66cdf491f97c)
