### ISSUE TITLE
IK of foot does not work well

### ISSUE THREAD

**Issue by KEITER78** [FlailingFog/KK-Blender-Porter-Pack#475]
As shown in the image, when I move the IK bone of the foot, the foot do not follow the bone properly. 
No matter where I move this bone, the character's knee stays straight and never bends.
How can I fix this?

The following is the character I used. I changed only the height of the default character. I have the latest HFpatch installed.

![Koikatu_F_20231002031300844_test test](https://github.com/FlailingFog/KK-Blender-Porter-Pack/assets/88971043/5bf57ab5-e709-403f-8af5-ffdc60878a69)

![Blender_chara](https://github.com/FlailingFog/KK-Blender-Porter-Pack/assets/88971043/7f42b0fd-5f3e-477e-862e-0ff89cc4e276)

**Comment by MrZackarias** [comment]
I can attest to this bug still happening on the latest version.
As a quick temporary workaround for anyone else having this problem, go in to the second layer of the armature and rotate the "Right knee" and "Left knee" bones forward just a little,

**Comment by Jonah-multi** [comment]
![image](https://github.com/user-attachments/assets/88312361-7208-4b1e-9206-eb576efeb3ee)
![image](https://github.com/user-attachments/assets/205a8d6a-62be-4bd9-a30f-f40c555d6a3d)
This issue is still present in KKBP 7.0.0, solution still works as well, under Layer "1"
(Image is a before and after of rotating knee)
