### ISSUE TITLE
Old Animation Import

### ISSUE THREAD

**Issue by shadow189** [FlailingFog/KK-Blender-Porter-Pack#483]
Hi, I would like the old single animation importer, is it possible? I don't want an animation library, only a single animation.

**Comment by FlailingFog** [comment]
I think the animation library is better because it's reusable that way. There's also nothing stopping you from importing only one animation using the animation library feature.

If you want to import only a single animation without creating an animation library, you can do that using the Rokoko plugin: https://www.youtube.com/watch?v=Nyxeb48mUfs&t=713s

The bone mappings for retargeting koikatsu animations to the KKBP Rigify armature can be found here: https://github.com/FlailingFog/KK-Blender-Porter-Pack/blob/master/extras/animationlibrary/Rokoko%20retargeting%20list%20(koikatsu%20fbx%20to%20KKBP%20Rigify).json

**Comment by shadow189** [comment]
Thanks, it helps me a lot

**Comment by shadow189** [comment]
But fingers does not work well with it

**Comment by shadow189** [comment]
I find a solution
