### ISSUE TITLE
Blue Colors defaulting for colormasks when importing a model (Koikatsu Sunshine)

### ISSUE THREAD

**Issue by Datta4486** [FlailingFog/KK-Blender-Porter-Pack#535]
![image](https://github.com/FlailingFog/KK-Blender-Porter-Pack/assets/86353399/9c9ed209-cfef-4ba3-b4de-6ebc9c48f2ba)

When I import a character, the customizable colors automatically defaults to blue causing this weird effect

![image](https://github.com/FlailingFog/KK-Blender-Porter-Pack/assets/86353399/e38cf4ae-3dd0-4b3a-84b8-958ac767a89b)
It is most apparent near the breasts and the crotch area, affecting the nipples and such. [I think Github doesn't like showing NSFW images]

![93188206_p1](https://github.com/FlailingFog/KK-Blender-Porter-Pack/assets/86353399/d1495747-518e-4567-9b5a-bf278575e794)
The card I am using for this [Originally for Koikatsu]

![image](https://github.com/FlailingFog/KK-Blender-Porter-Pack/assets/86353399/24eb983d-e978-408e-9701-6f65ffff9a8a)
I thought that since I was using a card that is originally meant for Koikatsu, I've imported a default character (Haneda Eiri) into blender. Well, while it had fixed those blue lines on the body, it also has its fair share of issues.

I am not well acquainted with how this game works and what does Skin Type/Detail etc. stuff actually means so any help will be appreciated :) [ I hope this info is more than enough otherwise just ask me for more.]

**Comment by StefanoVR17** [comment]
Bump, i have the same issue

**Comment by videoman614** [comment]
KK doesn't have this issue while KKS does.
Related to #471.

Bit of a hassle but you can manually fix the colors in blender.

**Comment by StefanoVR17** [comment]
> KK doesn't have this issue while KKS does. Related to #471.
> 
> Bit of a hassle but you can manually fix the colors in blender.

How it is possible? amd i guess to have it easier i might download KK, dunno yet, would like to hear more from your experience if you want to share it, thanks in any case

**Comment by Datta4486** [comment]
> > KK doesn't have this issue while KKS does. Related to #471.
> > Bit of a hassle but you can manually fix the colors in blender.
> 
> How it is possible to fix it in blender? and i guess to have it easier i might download KK, dunno yet, would like to hear more from your experience if you want to share it, thanks in any case

![image](https://github.com/FlailingFog/KK-Blender-Porter-Pack/assets/86353399/266253df-b2b5-4ef6-9009-36c45f088c81)

Go to the shading tab and select  the material and go into its group and change

**Comment by Datta4486** [comment]
> KK doesn't have this issue while KKS does. Related to #471.
> 
> Bit of a hassle but you can manually fix the colors in blender.

I used to have Koikatsu and never had its issue, but you can't import nude models without screwing up something. I am trying port characters to SFM, and the nude model is used as the base while the clothes are for body groups (toggable parts)

**Comment by FlailingFog** [comment]
Sorry, as noted in https://github.com/FlailingFog/KK-Blender-Porter-Pack/issues/471#issuecomment-1741808281 it looks like the Koikano shader is not supported by the V4.30 exporter. The KK_MaterialData.json you get with the pmx export does not have a "ShaderPropColorValues" value, so the blender importer will default to the cyan and yellow colors. What I didn't realize at the time was that the Koikano shader was the **_default shader for Sunshine_**...

I don't have the source code, but if @mediamoots is still around they may be interested in updating the exporter plugin to work with the Koikano shader again. 

Another potential fix is that I can likely update the blender plugin to handle exports from both the V4.21 exporter and the V4.30 exporter. This way KK users could export with V4.30 and KKS users could export with V4.21.

And to summarize the workarounds:
* The colors can be manually set in the blender shader nodes as described above
* The V4.21 exporter works correctly on KKS, but you will have to use KKBP V6.5.0, KKBP exporter V4.21, and Blender 3.5
* Using MaterialEditor in the game to change each shader from "Koikano hair_main_sun, main_clothes, main_skin" to "Shader Forge main_hair, main_item, main_skin" etc seem to fill the "ShaderPropColorValues" array with real values again. This works on the latest V4.30 exporter

**Comment by Guerra24** [comment]
Hello!

I've been dealing with this issue for a while now and already did the shader swap thing using MaterialEditor a couple of times and that was an absolute PAIN, so decided to give it a shot and decompile the plugin to try to fix this... which was quite easy, actually.

Turns out, the plugin hard-codes shader configuration parameters, which means it will only try to load *Shader Forge* (and some other variants) but not the *Koikano* shaders. 
![image](https://github.com/user-attachments/assets/fee1c389-6f68-44a4-9b77-ab25892e1e95)

So I added them to the list and it just worked. This is basically the same as swapping the shaders, but without going through that.
![image](https://github.com/user-attachments/assets/40b577d9-c709-4cd2-981d-9ee33fac7a67)

Did a quick export/import and everything appears to be fine, colors look fine. Did a couple of tests, but even with my patch it might miss some obscure shader used for some cloth piece or something like that. Of course because the shaders are not exactly the same it will look slightly different, specially the shaded/darkened textures since KKS uses a lighter shadow color.

If @MediaMoots is still around and wants to do this, just let me know and I will remove this patched plugin. Otherwise, @FlailingFog just let me know if anything breaks and I will try to fix it.

[KKBP_Exporter.zip](https://github.com/user-attachments/files/16592679/KKBP_Exporter.zip)

PSA: this will only work with KKS and was compiled with the latest HF patch.

**Comment by FlailingFog** [comment]
@Guerra24 
Hey, thanks a lot for this fix! I tried it and everything seems to work. If you don't mind, I'll add it to the next release so both KKS and KK can use the same plugin version.

**Comment by Guerra24** [comment]
Glad to hear! Sure, go for it.

**Comment by FlailingFog** [comment]
> Glad to hear! Sure, go for it.

Awesome, I've added it. I was also wondering, would you be willing to post the decompiled source code?
It would be nice to have the source for the plugin be publicly available in some form.

**Comment by Guerra24** [comment]
[Guerra24/KKBP_Exporter](https://github.com/Guerra24/KKBP_Exporter)

V4.30 decompiled + KKS patch. For building it just place the required dlls in deps and that's it.

**Comment by FlailingFog** [comment]
Thank you again! The exporter has essentially been closed source until now, so I really appreciate this.

**Comment by Datta4486** [comment]
> Thank you again! The exporter has essentially been closed source until now, so I really appreciate this.

Wdym closed source?

**Comment by FlailingFog** [comment]
> Wdym closed source?

I mean I have not seen any source code for the KKBP_Exporter.dll until now. There was [source code available for the original plugin it was based on](https://github.com/Snittern/KoikatsuPmxExporterReverseEngineered), but not the exporter itself.

**Comment by Guerra24** [comment]
@FlailingFog Updated the plugin, missed a shader used by some accessories.

[KKBP_Exporter.zip](https://github.com/user-attachments/files/16653078/KKBP_Exporter.zip)

**Comment by FlailingFog** [comment]
> @FlailingFog Updated the plugin, missed a shader used by some accessories.
> 
> [KKBP_Exporter.zip](https://github.com/user-attachments/files/16653078/KKBP_Exporter.zip)

Thanks! I've added it.

**Comment by Datta4486** [comment]
> > Go to the shading tab and select the material and go into its group and change
> 
> Hi, @Datta4486, do you have a picture thats a lot, LOT bigger and readable? I have the exact same issue, and my shader doesnt look that... I think. Because I can't see :(

Well, I am not currently on my PC rn to take a screenshot but I will try to explain how.  Go to the shading tab and select a material ( KK Body material). Then search for a node named body shader ( The name would be written on the nodes or kept in an area which is colored and named so). On the top right corner of the nodes, there would be a icon which is the nodes group icon. Just click it and you will be taken to its group. There you can change the colors of your model if it's default colors are blue. ( Note, Try experimenting with changing both nodes colors as some aren't visible to change at all)

**Comment by Datta4486** [comment]
@FlailingFog Unrelated but can you explain a bit more on the bone layers, like what does each layer does, what does cf_s and cf_d means? Thanks in advance!

**Comment by FlailingFog** [comment]
This is fixed in kkbp 7.0.0, so closing

> @FlailingFog Unrelated but can you explain a bit more on the bone layers, like what does each layer does, what does cf_s and cf_d means? Thanks in advance!

Sorry, I saw this but I forgot to respond. I don't really know exactly what they are, but I think the cf_s bones are the bones that are used in the character creator and I think the cf_d bones are the bones used for joint corrections when the arms and legs are bent. You can probably get better information on the armature from someone in the koikatsu discord

I made this reference chart like two years ago and it hasn't changed since then so here's all the other layers:
![arm1](https://github.com/user-attachments/assets/ba923ff1-7e4e-4567-a7ca-3c066faf5423)
