### ISSUE TITLE
[Question] Does this support KKS BetterRepack?

### ISSUE THREAD

**Issue by kz-n** [FlailingFog/KK-Blender-Porter-Pack#560]
I've had issues in the past with trying to use this mod in conjunction with KKS and the latest version of BR available, in short nothing worked about the export, maybe i got a complete model to show up on blender but it lacked any texture (or they were wrong ones) and it displayed the wrong outfit.
Even the default character when you start the editor had the same fate, So I'm wondering what's the official compatibility of this plugin like with KKS and the mods in BR

**Comment by FlailingFog** [comment]
Hey, please see https://github.com/FlailingFog/KK-Blender-Porter-Pack/issues/535 for KKS compatibility. There's some workarounds in there.
Additionally, BR is not supported because it is missing a pose plugin, but if you update the plugins as described in https://github.com/FlailingFog/KK-Blender-Porter-Pack/issues/523 it should work.

**Comment by UKPMAN** [comment]
@kz-n you have to install this mod to add the T-pose to KKS BR 
[](https://sideload.betterrepack.com/download/KKEC/Sideloader%20Modpack%20-%20Exclusive%20KKS/DeathWeasel/%5bDeathWeasel%5d%20Character%20Maker%20Poses%20v1.0.zipmod)
