### ISSUE TITLE
Color randomly becomes desaturated in blender

### ISSUE THREAD

**Issue by johnvo0918** [FlailingFog/KK-Blender-Porter-Pack#582]
Upon importing the colors will look correct but after a while it will be randomly desaturated.
Sometimes even on import the colors will be desaturated.
Sample:
how it looks upon importing:

![image](https://github.com/user-attachments/assets/55b313fa-b068-48ea-8980-2bbfd9394f89)

After awhile, I did not do anything to it, not even a tweak in shaders nor color management.

![image](https://github.com/user-attachments/assets/ad7ce00d-0ea1-44b4-8afe-12d01ec97335)

reopening the file does not fix this problem. Happens on all cards. I'll be tracking this closely.

My own card:

![Koikatu_F_20240722163803473_Kaiz Optimized_K](https://github.com/user-attachments/assets/b64d3fe4-a293-4f8e-9e45-d60614c946ed)
Card has a million outfits cuz I needed them separated for performance and minimize duplicated meshes.

**Comment by dddder4** [comment]
me too.

**Comment by FlailingFog** [comment]
This likely happens because you didn't save the saturated images. If you import a character, save the file and then exit blender without saving the images or you load a new file without saving the images it will reload the original desaturated image the next time you open it. 
You can either close blender after importing and it will prompt you to save the images, or you can click this button in the image editor and it will save the saturated images:
![image](https://github.com/user-attachments/assets/67cba117-a1a3-47ae-8a9a-033009b65d48)

This will be fixed in KKBP 7.0.0 because it automatically saves the images in that version, so there's no chance of desaturation

**Comment by johnvo0918** [comment]
thanks!
