### ISSUE TITLE
7.0.0 Eyes are wrong... 

### ISSUE THREAD

**Issue by johnvo0918** [FlailingFog/KK-Blender-Porter-Pack#606]
Very happy with the update.
No idea why my eyes are stretched like this. I've done nothing to the eyes. the only thing changed about the card was additional outfit slots.
![image](https://github.com/user-attachments/assets/adf24fe4-7c80-4749-8dcf-8447c540672b)
card

![Uploading Koikatu_F_20240903172128112_Kaiz Optimized_K.png…]()

**Comment by johnvo0918** [comment]
![Koikatu_F_20240903172128112_Kaiz Optimized_K](https://github.com/user-attachments/assets/0a9ba6da-8fbd-4e71-b5ae-c04286aae8cf)
I can't attach the card in the original post for some reason.

**Comment by FlailingFog** [comment]
I see what you mean. I tracked it down the Eye Textures node group. I have no idea why, but once I copy pasted the Eye Textures node group from kkbp 6.6.3 it started working. The node groups between the two versions should be exactly the same, so I don't know why it's stretched in 7.0.0. 
![image](https://github.com/user-attachments/assets/0eadd42e-248f-4e24-b763-4cf8972b0e3c)

I also deleted everything in the eye texture group except for the premade eye texture, created a new image node and it still didn't fix the stretched eye. Only the image node copy pasted from kkbp 6.6.3 made it normal so really not sure wtf is going on. 
![image](https://github.com/user-attachments/assets/5d2173fc-6133-4f36-85cd-5304666ba601)

As a workaround, you can scale the eyes back down in the eye positioning group, it looks like these values about do it
![image](https://github.com/user-attachments/assets/b2bfd57d-3fee-40f1-926a-a9d3d1b25239)

**Comment by johnvo0918** [comment]
thanks dawg ! I will be trying!

**Comment by johnvo0918** [comment]
Yup, it worked but the saturation method makes everything so yellow I can't really move forward with making my model. Please update the saturation settings soon!

**Comment by johnvo0918** [comment]
Oh I see 7.0.1 is out. imma try that

**Comment by FlailingFog** [comment]
Finally found out what was happening with the eyes. The UV mapping is completely correct in blender 4.2. The mapping was actually wrong in blender 3.6 and was likely wrong for a very long time.

![hmm](https://github.com/user-attachments/assets/bd641cf2-4918-4ab9-8da9-21b807964653)

The reason it looks stretched is because the "Iris Height" option in the character creator is being ignored by the importer. You have it set to 65, but the default is 83, so it's stretching back out to 83. There's likely something I can do with the "PupilWidth" and "PupilHeight" parameters in the KK_ChaFileCustomFace.json file to set the scaling group I showed above, but I'm not really sure how to use that info yet. For now I'm just going to make the importer put 1/pupil_height into the group to make it look somewhat correct.
