### ISSUE TITLE
KKBP 7.2.0 (and 7.1.0) crashing on finalize materials with create atlas on, am I doing something wrong?

### ISSUE THREAD

**Issue by Icyberg2** [FlailingFog/KK-Blender-Porter-Pack#631]
![image](https://github.com/user-attachments/assets/efbb668a-7cc7-4b53-9aab-4b383c6a120d)
So somehow I keep getting a crash to where I can't make an atlas file for any character I try to import, I don't understand if its maybe a mod attached to these models I'm using or if the program really can't handle generating an atlas file. I've tried going down to Blender 3.6.9 and KKBP 6.6.x but it still ends up failing to make an atlas file. I've been troubleshooting for about 2 to 3 days now with no luck.

**Comment by FlailingFog** [comment]
The new atlas generation takes a lot of ram, especially if the model has a lot of materials. If you check task manager while the process is running, maybe blender is maxing out your ram and crashing because of that? I plan on doing something with this feature eventually because I found while testing very complex models it needed like 10GB of ram to create the atlas, which is absurd.

I've found it has a lower chance of crashing on models with lots of materials if you click the finalize button with atlas creation disabled, wait for it to finish, then save and restart blender and click finalize again with atlas creation enabled. If that doesn't work you can also try selecting the clothes object and click the "split objects" button below the finalize button and it'll split the amount of materials the plugin has to deal with into two, so it'll make it less likely to crash. You also might want to try importing the default model when you open the character creator and see if you can get it to create an atlas for that one.

**Comment by Icyberg2** [comment]
So I tried with a different model this time and tried the split object idea.. but nope, it still ends up crashing. I'm gonna try the default but I did watch task manager just to see what the RAM usage was when generating an atlas, it managed to use up to 25GB of my 32GB RAM. I've never seen such high RAM usage to that degree and it ended up crashing the same way it's been doing.
