### ISSUE TITLE
Rendering with Cycles

### ISSUE THREAD

**Issue by yuyuki** [FlailingFog/KK-Blender-Porter-Pack#77]
Hi,

First of all, thank a lot for this great job.

I've a question which concerns Cycles.
When I render the file with Evee, it works like a charm.
But not in Cycles.
Everything stay black.

I try to check the trick with the transparency issue but it seems fine. I look at this tutoriel https://www.youtube.com/watch?v=S2bqqnEgudA

Can you explain me what I need to do ?
[](url)[
I use the version :](url)
* KK-Blender-Shader-Pack-5-merger
* [cats-blender-plugin-0-19-0]([url](url))
 
Here is the link WebTransfert to my Blender file : https://we.tl/t-2DNdi1qNqc

Thank you

**Comment by FlailingFog** [comment]
The shader uses a "Shader to RGB" node that is not available in Cycles.
If you want to use it in Cycles you can probably use the Atlas Generator in CATS to make it work, so these
![image](https://user-images.githubusercontent.com/65811931/144309043-c6e12cd6-c17b-43ae-96b4-77269af0b1dc.png)
And this in the CATS tab
![image](https://user-images.githubusercontent.com/65811931/144309113-a1da357d-098a-449a-ae82-366c1eec0450.png)
And with the atlas you can use a normal Principled BSDF node in Cycles

**Comment by poisenbery** [comment]
![Screenshot (368)](https://user-images.githubusercontent.com/78466408/146504225-cf3a95dc-3341-429e-827b-b168c20b4a01.png)
POC of how to do it.

I encountered issues with alpha on the eyes and nose yesterday when I was testing.
Basic concept is to adjust the body shader settings and then use those as various maps. I haven't figured out a good method to do this yet, aside from using the maintex as the diffuse.

I took an output from the raw shading group that looked like a tangent space normal map, and routed it to the output. Then i fed that into a normal map node and put it into the bsdf's normal input, and it works in cycles.

Definitely needs more testing through, but if anyone else wants cycles renders with this, it IS possible.

**Comment by poisenbery** [comment]
@FlailingFog 
@yuyuki 

Managed to edit the KK Shader blend file to add a cycles "converter"
I had to change a couple of things for it to work:
![Screenshot (377)](https://user-images.githubusercontent.com/78466408/146575869-f6cdb5e8-88d1-44d6-ab96-78938991cc2e.png)
This node was set to shader when it didn't seem to have any shader data. Not sure if this was intentional, but the setup didn't work unless I changed the node type to Color in the group panel. It didn't seem to have any effect on the Eevee render view, but I also don't know a lot about that type of shading technique, so I'm not sure if it might have affected something.

I also had to "Bypass" all of the shader-> RGB nodes that were in the clothing/extras shader with a duplicated group. I'm not sure if my method was the best, but it seems to work fine in cycles:
![Screenshot (383)](https://user-images.githubusercontent.com/78466408/146582777-48465d82-3f07-4e38-bc4d-ae3b781f8e4e.png)



So for this to work, the user has to disable the solidify modifier in viewport and render, or else everything will be solid black in cycles. There also seems to be an issue with the faces of the "Template Eyeline Down" material intersecting with the face, which causes some issues in cycles:
![Screenshot (384)](https://user-images.githubusercontent.com/78466408/146582989-85291b35-f9ef-45aa-b34d-e95d38b037f4.png)

This can easily be fixed by selecting the faces associated with that material, and moving them along the Y axis until they no longer overlap with the face faces:
![Screenshot (385)](https://user-images.githubusercontent.com/78466408/146583224-ce375388-25ac-47d9-9fb7-1e32e84e789d.png)



I haven't noticed any issues yet. Let me know if this is useful. Just replace the KK Shader V5.0.blend in your blender addon folder, or include this in an updated version.
[Cycles Version.zip](https://github.com/FlailingFog/KK-Blender-Porter-Pack/files/7736725/Cycles.Version.zip)
.

**Comment by FlailingFog** [comment]
It should also be possible to stick the cycles version of the KK shader into the same directory the pmx file is in and it'll read from that file instead of the one integrated into the plugin. The eyeline down material is fully transparent so you can delete it instead of moving it if you want to.

**Comment by FlailingFog** [comment]
There's basic cycles support in 6.1.1 and later
