### ISSUE TITLE
Closed eye import issue

### ISSUE THREAD

**Issue by ghost** [FlailingFog/KK-Blender-Porter-Pack#81]
I found this issue has persisted for a while but hadn't have a chance to test it to see if it's koikatsu or the porter pack.

![ingame](https://user-images.githubusercontent.com/88926467/145775216-6a631527-ec73-4e18-b603-9904ef000632.png)
![blender](https://user-images.githubusercontent.com/88926467/145775226-60c15e67-a366-439f-a11c-856c92242b36.png)

There seems to be an issue whenever I import into blender, the eye looks normal in the game when it's closed but it seems to deform whenever the model is imported. This issue is still present in ebca409.

**Comment by MediaMoots** [comment]
When exporting, first make sure to set all animations to default/none especially eye/mouth shapes.

**Comment by lurkingaround** [comment]
> When exporting, first make sure to set all animations to default/none especially eye/mouth shapes.

I think the exporter automatically adjusts the settings before it exports but I always so that anyway and still get this issue unfortunately.

**Comment by MediaMoots** [comment]
I think this is because KK only set the blend shape to .5 max?

**Comment by lurkingaround** [comment]
Ah, should I close this? I can always set the shapekeys back to .5 instead if 1 but I'm probably not the only one confused by this.

**Comment by FlailingFog** [comment]
I believe this is a shortcoming with each of the known Koikatsu exporters (PMX, KKBP and GME).

I'm pretty sure Koikatsu uses both shapekeys **and** the face bones to create expressions. I think it keeps track of how far the face sliders in the charamaker have been modified from the default face settings, and then uses that info to temporarily move the bones a certain way during each expression. Instead of using the shapekey on a modified face that may or may not work for every expression, they're using the shapekey on a known face that will look good every time. If that theory is right, then none of the exporters can replicate the in-game behaviour because they only export the "modified" armature with the sliders applied and not the "default" armature that the game uses as a reference.

If the default armature was exported alongside the modified armature (and I'm correct in my assumptions), the shapekeys with the bone corrections could probably be automatically generated, but that would require a lot of work figuring out what bones go in what directions for what expressions.

The workaround I've been using for this is taking the shapekeys I'll need (not all of them) and stretching them around with proportional editing mode so they look right.

**Comment by lurkingaround** [comment]
Thanks for the explanation. Makes sense, I'll close the issue to reduce clutter.

**Comment by MediaMoots** [comment]
PR #138
