### ISSUE TITLE
Imported textures are "lightned"

### ISSUE THREAD

**Issue by poisenbery** [FlailingFog/KK-Blender-Porter-Pack#85]
The best way to show this are to provide examples
![acs_horn10_MainTex](https://user-images.githubusercontent.com/78466408/146682755-1b772b80-4438-4788-956c-d587d5db30e6.png)
![acs_horn10 -3637914_MainTex_CT](https://user-images.githubusercontent.com/78466408/146682764-17805082-9de5-4332-9924-e1b45969f4c4.png)
![acs_horn10 -3637930_MainTex_CT](https://user-images.githubusercontent.com/78466408/146682766-1cd19346-4654-410f-b330-b198df0597a9.png)
.

The first image was extracted with Greys Mesh Exporter.
The bottom 2 came from the KKBP tool.

As you can tell, the bottom 2 are lighter and seem to lose some of the detail in the texture.
![cf_m_hitomi_00_MainTex](https://user-images.githubusercontent.com/78466408/146682910-0853d25f-f78f-4e90-b491-c08a3a433674.png)
![cf_m_hitomi_00_MainTex_CT](https://user-images.githubusercontent.com/78466408/146682914-3ccc526f-a549-468b-8990-5c696960b172.png)

It is extremely noticeable on anything that has color. I imagine that this also has a negative effect on normal and detail maps.
![Xmas_bell_m_NormalMap](https://user-images.githubusercontent.com/78466408/146682950-da0899f2-72aa-4e44-8570-9628882dcdc0.png)
![Xmas_bell_m -3638260_NormalMap](https://user-images.githubusercontent.com/78466408/146682952-df55acc5-1466-4843-b637-69c43adaf863.png)

**Comment by MediaMoots** [comment]
Hi there, this is because KK applies a LUT to all colors in game, so source textures appear lighter without the LUT.

GME applies a color filter to the exported textures (Not the LUT but something else).

KKBP on the other hand exports the original textures, we then convert the textures with some custom code in the Blender Plugin that uses the original KK LUT to convert the textures/colors back to how they would look in game.

By using the workflow provided with KKBP (dll and blender plugin) you will get 99.9% the original KK look.

**Comment by poisenbery** [comment]
> By using the workflow provided with KKBP (dll and blender plugin) you will get 99.9% the original KK look.

Ahhhh ok, this is a "me" problem then. 

I actually edited the shader group pack to render in cycles, so my use of the addon seems to be outside of the scope of what it's actually supposed to be used for.
